#!/usr/bin/perl
use warnings;
use strict;
#

sub main() {
    my $until = $ARGV[0];

    my $now = time();
    my $seconds = $until - time();

    if ($seconds < 0) {
        die("Target already past");
    }

    sleep($seconds);
}

main();

