---
name: ci

# yamllint disable-line rule:truthy
on:
  pull_request:
  release:
    types:
      - published
      - created
      - edited
  workflow_dispatch:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fix Checkout
        run: |
          git fetch --force --tags

      - name: Install essential
        run: |
          sudo apt update
          make build-dep

      - name: Run the ci
        run: |
          make -k lint
